services:
  Store.Books.domain.BookRepository:
    class: ../../../../../contexts/store/book/infrastructure/persistence/MongoBookRepository
    arguments: ['@Store.Shared.ConnectionManager']

  Store.Books.domain.BookEventStore:
    class: ../../../../../contexts/store/book/infrastructure/persistence/MongoBookEventStore
    arguments: ['@Store.Shared.ConnectionManager']

  Store.Books.application.BookCreator:
    class: ../../../../../contexts/store/book/application/create/book-creator
    main: BookCreator
    arguments: ['@Store.Shared.domain.EventBus', '@Store.Books.domain.BookEventStore']

  Store.Books.CreateBookCommandHandler:
    class: ../../../../../contexts/store/book/application/command-handlers/create-book-command-handler
    main: CreateBookCommandHandler
    arguments: ['@Store.Books.application.BookCreator']
    tags:
      - { name: 'commandHandler' }

  Store.Books.application.BooksFinder:
    class: ../../../../../contexts/store/book/application/SearchAll/BooksFinder
    arguments: ['@Store.Books.domain.BookRepository']

  Store.Books.SearchAllBooksQueryHandler:
    class: ../../../../../contexts/store/book/application/SearchAll/SearchAllBooksQueryHandler
    arguments: ['@Store.Books.application.BooksFinder']
    tags:
      - { name: 'queryHandler' }

  Store.Books.CreateBookOnBookCreated:
    class: ../../../../../contexts/store/book/application/event-handlers/book-created-event-handler
    main: BookCreatedEventHandler
    arguments: ['@Store.Books.domain.BookRepository']
    tags:
      - { name: 'domainEventSubscriber' }

  Store.Books.application.BooksByCriteriaSearcher:
    class: ../../../../../contexts/store/book/application/SearchByCriteria/books-by-criteria-searcher
    main: BooksByCriteriaSearcher
    arguments: ['@Store.Books.domain.BookRepository']

  Store.Books.SearchBooksByCriteriaQueryHandler:
    class: ../../../../../contexts/store/book/application/SearchByCriteria/search-books-by-criteria-query-handler
    main: SearchBooksByCriteriaQueryHandler
    arguments: ['@Store.Books.application.BooksByCriteriaSearcher']
    tags:
      - { name: 'queryHandler' }
