version: '3.5'

services:

  api:
    image: node:17.6-alpine
    container_name: tba-api
    depends_on:
      - redis
    working_dir: /app
    volumes:
      - ./:/app
      - ./node_modules/:/node_modules
    ports:
      - "3000:3000"
    command: sh -c "yarn && yarn dev"

  ui:
    image: node:17.6-alpine
    container_name: tba-ui
    working_dir: /app
    volumes:
      - ./ui/:/app
      - ./ui/node_modules/:/node_modules
    ports:
      - "4200:4200"
      - "9876:9876"
    command: sh -c "npm install && npm run start"
  
  redis:
    image: redis:5-alpine
    container_name: tba-redis
    ports:
      - "6379:6379"
    env_file:
    - .env
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}