version: '2.1'

services:

  shop_backend:
    image: node:lts-alpine3.18
    container_name: shop-backend
    environment:
      - HOSTNAMERABBIT=rabbitmq
      - CLOUDAMQP_URL=amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./:/app
      - ./node_modules/:/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

  rabbitmq:
    image: 'rabbitmq:3.8-management'
    container_name: shop-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 10s
        timeout: 10s
        retries: 5

  

  shop_frontend:
    image: node:18.17-alpine
    container_name: shop-frontend
    working_dir: /app
    volumes:
      - ./src/apps/shop/frontend/:/app
      - ./src/apps/shop/frontend/node_modules/:/node_modules
    ports:
      - "4200:4200"
      - "9876:9876"
    command: sh -c "npm install && npm run start"