services:
    backend_test:
        image: node:24.15-alpine
        container_name: backend-test
        depends_on:
            kafka_test:
                condition: service_healthy
        working_dir: /app
        volumes:
            - ./:/app
            - ./node_modules/:/node_modules
        ports:
            - "5002:5002"
        command: sh -c "npm install && npm run test:features"

    kafka_test:
        image: confluentinc/cp-kafka:7.6.1
        container_name: kafka-test
        hostname: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
            CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

        volumes:
            - kafka-data:/var/lib/kafka/data

        healthcheck:
            test:
                [
                    "CMD",
                    "kafka-topics",
                    "--list",
                    "--bootstrap-server",
                    "kafka:9092",
                    "--list",
                ]
            interval: 10s
            timeout: 10s
            retries: 10

    mongo:
        image: mongo:6.0.9
        container_name: mongo-test
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongouser
            MONGO_INITDB_ROOT_PASSWORD: super-secret-password
            MONGO_INITDB_DATABASE: shop_test
        volumes:
            #- ./data/mongo:/data/db:delegated
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports:
            - 27017:27017

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
        container_name: elasticsearch-test
        healthcheck:
            test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
            interval: 30s
            timeout: 10s
            retries: 50
        environment:
            - node.name=elasticsearch-test
            - discovery.type=single-node #Elasticsearch forms a single-node cluster
            - bootstrap.memory_lock=true # might cause the JVM or shell session to exit if it tries to allocate more memory than is available!
            - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
            - xpack.security.enabled=false
            - xpack.security.http.ssl.enabled=false
        ulimits:
            memlock:
                soft: -1 # The memlock soft and hard values configures the range of memory that ElasticSearch will use. Setting this to –1 means unlimited.
                hard: -1
        ports:
            - "9200:9200"
