version: '2.1'

services:

  shop_backend_test:
    image: node:lts-alpine3.18
    container_name: shop-backend-test
    environment:
      - HOSTNAMERABBIT=rabbitmq
      - CLOUDAMQP_URL=amqp://rabbitmq:5672
    depends_on:
      rabbitmq_test:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./:/app
      - ./node_modules/:/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run test-features"

  rabbitmq_test:
    image: 'rabbitmq:3.8-management'
    container_name: tba-rabbitmq-test
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 10s
        timeout: 10s
        retries: 5