x-node-service: &node-service
    build:
        context: .

    init: true

    working_dir: /app

    volumes:
        - ./:/app
        - backend_node_modules:/app/node_modules

services:
    backend:
        <<: *node-service
        depends_on:
            kafka-configurer:
                condition: service_completed_successfully
        ports:
            - "5001:5001"
        healthcheck:
            test:
                [
                    "CMD",
                    "node",
                    "-e",
                    "fetch('http://localhost:5001/healthcheck').then(r=>process.exit(r.ok?0:1))",
                ]
            interval: 10s
            timeout: 5s
            retries: 3

        command: sh -c "npm run dev:shop:backend"

    backoffice-backend:
        <<: *node-service
        depends_on:
            backend:
                condition: service_healthy
        ports:
            - "3000:3000"
        healthcheck:
            test:
                [
                    "CMD",
                    "node",
                    "-e",
                    "fetch('http://localhost:5001/healthcheck').then(r=>process.exit(r.ok?0:1))",
                ]
            interval: 10s
            timeout: 5s
            retries: 3
        command: sh -c "npm run dev:backoffice:backend"

    importer:
        <<: *node-service
        depends_on:
            backend:
                condition: service_healthy
        command: sh -c "npm run dev:importer"

    mongo:
        image: mongo:6.0.9
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongouser
            MONGO_INITDB_ROOT_PASSWORD: super-secret-password
            MONGO_INITDB_DATABASE: shop
        volumes:
            #- ./data/mongo:/data/db:delegated
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        ports:
            - 27018:27017

    kafka:
        image: confluentinc/cp-kafka:7.6.1
        hostname: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
            CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

        # volumes:
        #     - kafka-data:/var/lib/kafka/data

        healthcheck:
            test:
                [
                    "CMD",
                    "kafka-topics",
                    "--list",
                    "--bootstrap-server",
                    "kafka:9092",
                    "--list",
                ]
            interval: 10s
            timeout: 10s
            retries: 10

    kafka-configurer:
        <<: *node-service
        depends_on:
            kafka:
                condition: service_healthy
        command: sh -c "node -r ts-node/register -r tsconfig-paths/register src/scripts/configure-shop-kafka.ts"

    kafbat-ui:
        image: ghcr.io/kafbat/kafka-ui:latest
        depends_on:
            kafka:
                condition: service_healthy
        ports:
            - 8080:8080
        environment:
            DYNAMIC_CONFIG_ENABLED: "true"
        volumes:
            - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
        healthcheck:
            test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
            interval: 30s
            timeout: 10s
            retries: 50
        environment:
            - node.name=elasticsearch
            - discovery.type=single-node #Elasticsearch forms a single-node cluster
            - bootstrap.memory_lock=true # might cause the JVM or shell session to exit if it tries to allocate more memory than is available!
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
            - xpack.security.http.ssl.enabled=false
        ulimits:
            memlock:
                soft: -1 # The memlock soft and hard values configures the range of memory that ElasticSearch will use. Setting this to –1 means unlimited.
                hard: -1
        # volumes:
        #   - esdata:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
    kibana:
        image: docker.elastic.co/kibana/kibana:8.8.1
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        ports:
            - 5601:5601

    frontend:
        build:
            context: ./src/apps/shop/frontend
        working_dir: /app
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - ./src/apps/shop/frontend/:/app
            - frontend_node_modules:/app/node_modules
        ports:
            - "4200:4200"
            - "9876:9876"
        command: sh -c "npm run start"
volumes:
    backend_node_modules:
    frontend_node_modules:
