services:
  Store.Shared.MongoConfig:
    factory:
      class: ../../../../../contexts/store/shared/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  Store.Shared.ConnectionManager:
    factory:
      class: ../../../../../contexts/shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['backoffice', '@Store.Shared.MongoConfig']
  Store.Shared.CommandHandlers:
    class: ../../../../../contexts/shared/infrastructure/CommandBus/CommandHandlers
    arguments: ['!tagged commandHandler']

  Store.Shared.domain.CommandBus:
    class: ../../../../../contexts/shared/infrastructure/CommandBus/InMemoryCommandBus
    arguments: ['@Store.Shared.CommandHandlers']

  Store.Shared.RabbitMQConfig:
    factory:
      class: ../../../../../contexts/store/shared/infrastructure/RabbitMQ/RabbitMQConfigFactory
      method: 'createConfig'

  Store.Shared.domain.EventBus:
    factory:
      class: ../../../../../contexts/store/shared/infrastructure/RabbitMQ/RabbitMQEventBusFactory
      method: 'create'
    arguments:
      [
        '@Store.Shared.DomainEventFailoverPublisher',
        '@Store.Shared.RabbitMQConnection',
        '@Store.Shared.RabbitMQqueueFormatter',
        '@Store.Shared.RabbitMQConfig',
      ]

  Store.Shared.RabbitMQQueueFormatter:
    class: ../../../../../contexts/shared/infrastructure/EventBus/RabbitMQ/RabbitMQqueueFormatter
    arguments: ['store']

  Store.Shared.RabbitMQConnection:
    class: ../../../../../contexts/shared/infrastructure/EventBus/RabbitMQ/RabbitMqConnection
    arguments: ['@Store.Shared.RabbitMQConfig']

  Store.Shared.RabbitMQqueueFormatter:
    class: ../../../../../contexts/shared/infrastructure/EventBus/RabbitMQ/RabbitMQqueueFormatter
    arguments: ['store']

  Store.Shared.RabbitMQConfigurer:
    class: ../../../../../contexts/shared/infrastructure/EventBus/RabbitMQ/RabbitMQConfigurer
    arguments: ['@Store.Shared.RabbitMQConnection', '@Store.Shared.RabbitMQQueueFormatter']

  Store.Shared.DomainEventFailoverPublisher:
    class: ../../../../../contexts/shared/infrastructure/EventBus/DomainEventFailoverPublisher/DomainEventFailoverPublisher
    arguments: ['@Store.Shared.ConnectionManager']

  Store.Shared.QueryHandlers:
    class: ../../../../../contexts/shared/infrastructure/QueryBus/QueryHandlers
    arguments: ['!tagged queryHandler']

  Store.Shared.domain.QueryBus:
    class: ../../../../../contexts/shared/infrastructure/QueryBus/InMemoryQueryBus
    arguments: ['@Store.Shared.QueryHandlers']
