services:
  Apps.Shop.Backend.controllers.ProductPostController:
    class: ../../controllers/product-post-controller
    main: ProductPostController
    arguments: ['@Shop.Shared.domain.CommandBus']

  Apps.Shop.Backend.controllers.ProductGetAllController:
    class: ../../controllers/product-get-all-controller
    main: ProductGetAllController
    arguments: ['@Shop.Shared.domain.QueryBus']

  Apps.Shop.Backend.controllers.ProductGetByIdController:
    class: ../../controllers/product-get-by-id-controller
    main: ProductGetByIdController
    arguments: ['@Shop.Shared.domain.QueryBus']

  Apps.Shop.Backend.controllers.ProductGetByCriteriaController:
    class: ../../controllers/product-get-by-criteria-controller
    main: ProductGetByCriteriaController
    arguments: ['@Shop.Shared.domain.QueryBus']

  Apps.Shop.Backend.controllers.ProductPutDescriptionController:
    class: ../../controllers/product-put-description-controller
    main: ProductPutDescriptionController
    arguments: ['@Shop.Shared.domain.CommandBus']

  Apps.Shop.Backend.controllers.ProductPutImageController:
    class: ../../controllers/product-put-image-controller
    main: ProductPutImageController
    arguments: ['@Shop.Shared.domain.CommandBus']

  Apps.Shop.Backend.controllers.UserPostController:
    class: ../../controllers/user-post-controller
    main: UserPostController
    arguments: ['@Shop.Shared.domain.CommandBus']

  Apps.Shop.Backend.controllers.UserGetAllController:
    class: ../../controllers/user-get-all-controller
    main: UserGetAllController
    arguments: ['@Shop.Shared.domain.QueryBus']

  Apps.Shop.Backend.controllers.UserGetByIdController:
    class: ../../controllers/user-get-by-id-controller
    main: UserGetByIdController
    arguments: ['@Shop.Shared.domain.QueryBus']

  Apps.Shop.Backend.controllers.UserGetByCriteriaController:
    class: ../../controllers/user-get-by-criteria-controller
    main: UserGetByCriteriaController
    arguments: ['@Shop.Shared.domain.QueryBus']

  Apps.Shop.Backend.controllers.UserPutController:
    class: ../../controllers/user-put-controller
    main: UserPutController
    arguments: ['@Shop.Shared.domain.CommandBus']

  Apps.Shop.Backend.controllers.UserPutPasswordController:
    class: ../../controllers/user-put-password-controller
    main: UserPutPasswordController
    arguments: ['@Shop.Shared.domain.CommandBus']

  Apps.Shop.Backend.controllers.LoginPostController:
    class: ../../controllers/login-post-controller
    main: LoginPostController
    arguments: ['@Shop.Shared.domain.CommandBus', '@Shop.Shared.domain.QueryBus']

  Apps.Shop.Backend.controllers.LoginRenewGetController:
    class: ../../controllers/login-renew-get-controller
    main: LoginRenewGetController
    arguments: ['@Shop.Shared.domain.QueryBus']
