services:
    Shared.Logger:
        class: ../../../../contexts/shared/infrastructure/winston-logger
        main: WinstonLogger
        arguments: []
    Shared.MongoConfig:
        factory:
            class: ../../../../contexts/importer/shared/infrastructure/persistence/mongo/mongo-config-factory
            main: MongoConfigFactory
            method: "createConfig"

    Shared.ConnectionManager:
        factory:
            class: ../../../../contexts/shared/infrastructure/persistence/mongo/mongo-client-factory
            main: MongoClientFactory
            method: "createClient"
        arguments: ["importer", "@Shared.MongoConfig"]

    Shared.CommandHandlers:
        class: ../../../../contexts/shared/infrastructure/command-bus/command-handlers
        main: CommandHandlers
        arguments: ["!tagged commandHandler"]

    Shared.domain.CommandBus:
        class: ../../../../contexts/shared/infrastructure/command-bus/in-memory-command-bus
        main: InMemoryCommandBus
        arguments: ["@Shared.CommandHandlers"]

    Shared.domain.EventBus:
        factory:
            class: ../../../../contexts/importer/shared/infrastructure/kafka/kafka-event-bus-factory
            main: KafkaEventBusFactory
            method: "create"
        arguments:
            [
                "@Shared.DomainEventFailoverPublisher",
                "@Shared.KafkaConnection",
                "@Shared.KafkaTopicFormatter",
                "@Shared.Logger",
            ]

    Shared.KafkaConfig:
        factory:
            class: ../../../../contexts/importer/shared/infrastructure/kafka/kafka-config-factory
            main: KafkaConfigFactory
            method: "createConfig"
    Shared.KafkaQueueFormatter:
        class: ../../../../contexts/shared/infrastructure/event-bus/kafka/kafka-topic-formatter
        main: KafkaTopicFormatter
        arguments: ["importer"]

    Shared.KafkaConnection:
        class: ../../../../contexts/shared/infrastructure/event-bus/kafka/kafka-connection
        main: KafkaConnection
        arguments: ["@Shared.KafkaConfig"]

    Shared.KafkaTopicFormatter:
        class: ../../../../contexts/shared/infrastructure/event-bus/kafka/kafka-topic-formatter
        main: KafkaTopicFormatter
        arguments: ["importer"]

    Shared.KafkaConfigurer:
        class: ../../../../contexts/shared/infrastructure/event-bus/kafka/kafka-configurer
        main: KafkaConfigurer
        arguments: ["@Shared.KafkaConnection", "@Shared.KafkaQueueFormatter"]

    Shared.DomainEventFailoverPublisher:
        class: ../../../../contexts/shared/infrastructure/event-bus/domain-event-failover-publisher/domain-event-failover-publisher
        main: DomainEventFailoverPublisher
        arguments: ["@Shared.ConnectionManager"]
