services:
  Shared.Logger:
    class: ../../../../../contexts/shared/infrastructure/winston-logger
    main: WinstonLogger
    arguments: []
  Shop.Shared.MongoConfig:
    factory:
      class: ../../../../../contexts/shop/shared/infrastructure/persistence/mongo/mongo-config-factory
      main: MongoConfigFactory
      method: 'createConfig'

  Shop.Shared.ConnectionManager:
    factory:
      class: ../../../../../contexts/shared/infrastructure/persistence/mongo/mongo-client-factory
      main: MongoClientFactory
      method: 'createClient'
    arguments: ['backoffice', '@Shop.Shared.MongoConfig']

  Shop.Shared.CommandHandlers:
    class: ../../../../../contexts/shared/infrastructure/command-bus/command-handlers
    main: CommandHandlers
    arguments: ['!tagged commandHandler']

  Shop.Shared.domain.CommandBus:
    class: ../../../../../contexts/shared/infrastructure/command-bus/in-memory-command-bus
    main: InMemoryCommandBus
    arguments: ['@Shop.Shared.CommandHandlers']

  Shop.Shared.RabbitMQConfig:
    factory:
      class: ../../../../../contexts/shop/shared/infrastructure/rabbitmq/rabbitmq-config-factory
      main: RabbitMQConfigFactory
      method: 'createConfig'

  Shop.Shared.domain.EventBus:
    factory:
      class: ../../../../../contexts/shop/shared/infrastructure/rabbitmq/rabbitmq-event-bus-factory
      main: RabbitMQEventBusFactory
      method: 'create'
    arguments:
      [
        '@Shop.Shared.DomainEventFailoverPublisher',
        '@Shop.Shared.RabbitMQConnection',
        '@Shop.Shared.RabbitMQqueueFormatter',
        '@Shop.Shared.RabbitMQConfig',
        '@Shared.Logger',
      ]

  Shop.Shared.RabbitMQQueueFormatter:
    class: ../../../../../contexts/shared/infrastructure/event-bus/rabbitmq/rabbitmq-queue-formatter
    main: RabbitMQqueueFormatter
    arguments: ['store']

  Shop.Shared.RabbitMQConnection:
    class: ../../../../../contexts/shared/infrastructure/event-bus/rabbitmq/rabbitmq-connection
    main: RabbitMqConnection
    arguments: ['@Shop.Shared.RabbitMQConfig']

  Shop.Shared.RabbitMQqueueFormatter:
    class: ../../../../../contexts/shared/infrastructure/event-bus/rabbitmq/rabbitmq-queue-formatter
    main: RabbitMQqueueFormatter
    arguments: ['store']

  Shop.Shared.RabbitMQConfigurer:
    class: ../../../../../contexts/shared/infrastructure/event-bus/rabbitmq/rabbitmq-configurer
    main: RabbitMQConfigurer
    arguments: ['@Shop.Shared.RabbitMQConnection', '@Shop.Shared.RabbitMQQueueFormatter']

  Shop.Shared.DomainEventFailoverPublisher:
    class: ../../../../../contexts/shared/infrastructure/event-bus/domain-event-failover-publisher/domain-event-failover-publisher
    main: DomainEventFailoverPublisher
    arguments: ['@Shop.Shared.ConnectionManager']

  Shop.Shared.QueryHandlers:
    class: ../../../../../contexts/shared/infrastructure/query-bus/query-handlers
    main: QueryHandlers
    arguments: ['!tagged queryHandler']

  Shop.Shared.domain.QueryBus:
    class: ../../../../../contexts/shared/infrastructure/query-bus/in-memory-query-bus
    main: InMemoryQueryBus
    arguments: ['@Shop.Shared.QueryHandlers']
