imports:
  - { resource: ./application.yaml }

services:
  Backoffice.EnvironmentArranger:
    class: ../../../../../tests/contexts/shared/infrastructure/elasticsearch/elastic-environment-arranger
    main: ElasticEnvironmentArranger
    arguments: ['@Backoffice.Shared.ElasticConnectionManager', '@Backoffice.Shared.ElasticConfig']
