imports:
  - { resource: ./application.yaml }

services:
  Backoffice.EnvironmentArranger:
    class: ../../../../../tests/contexts/shared/infrastructure/mongo/mongo-environment-arranger
    main: MongoEnvironmentArranger
    arguments: ['@Backoffice.Shared.ConnectionManager']
