imports:
  - { resource: ./apps/application.yaml }
  - { resource: ./shared/application.yaml }
  - { resource: ./products/application.yaml }
  - { resource: ./products-counter/application.yaml }
  - { resource: ./orders/application.yaml }
  - { resource: ./users/application.yaml }
  - { resource: ./carts/application.yaml }
